### PR TITLE
fixed `byrow=FALSE` reorder not only plots but also labels

### LINKED ISSUE #199: Labels in `plot_grid()` seemed not affected by `byrow`
Labels are always attached by row.

```{r}
p_list <- mtcars %>% split(.$gear) %>% map(~ggplot(.x,aes(x = mpg, y = disp)) + geom_point())
plot_grid(plotlist = p_list, ncol = 2, labels = names(p_list), byrow = F)
```
image

```{r}
p_list["4"]
```
image

### PR DESCRIPTION
**Pull request by Doubt-0KB**
This PR fixes an issue where the argument `byrow=FALSE` only reorders the plots, but not the labels. Closes #199.

Here is a demo of fixed function.

image

### CODE REVIEW

File: R/plot_grid.R [hunk 1]
```diff
@@ -177,8 +177,10 @@ plot_grid <- function(..., plotlist = NULL, align = c("none", "h", "v", "hv"),
   if (is.null(cols)) cols <- ceiling(num_plots/rows)
   if (is.null(rows)) rows <- ceiling(num_plots/cols)
 
-  # if the user wants to layout the plots by column, we use the calculated rows to reorder plots
-  if (!isTRUE(byrow)) plots <- plots[c(t(matrix(c(1:num_plots, rep(NA, (rows * cols) - num_plots)), nrow = rows, byrow = FALSE)))]
+  # if the user wants to layout the plots by column, we use the calculated rows to reorder plots and labels
+  if (!isTRUE(byrow)) 
+    plots <- plots[c(t(matrix(c(1:num_plots, rep(NA, (rows * cols) - num_plots)), nrow = rows, byrow = FALSE)))]
+    labels <- labels[c(t(matrix(c(1:num_plots, rep(NA, (rows * cols) - num_plots)), nrow = rows, byrow = FALSE)))]
```
Comment (clauswilke) [inline R/plot_grid.R:183]: Shouldn't this code block be enclosed in curly braces? Otherwise line 183 gets executed regardless of whether the condition is true or not, no? Either way, please add curly braces for clarity.

**Comment by clauswilke** [comment]
Apologies, yes, this is fine in principle. Is it possible to add a simple unit test that tests for the order of the labels in both arrangements?

Here is some starting code for the unit tests:
```r
p_list <- map(1:3, \(x) ggplot())
g <- plot_grid(plotlist = p_list, ncol = 2, labels = 1:3, byrow = FALSE)
layer_data(g, 4)
```
Just extract all the labels by making the relevant `layer_data()` calls and test that they are in the correct location and do this for both `byrow = FALSE` and `byrow = TRUE`.

**Comment by clauswilke** [comment]
@Doubt-0KB I don't know what you did with your last commit but it's not a clean diff. You probably messed up newlines. Please revert.

**Comment by Doubt-0KB** [comment]
Sorry, I'm not familiar with the operation and made a mistake. I will revert and commit again.

**Comment by Doubt-0KB** [comment]
I remove the visual tests, and add the tests using the code you posted.

**Comment by clauswilke** [comment]
Thanks!
